import { PerpDEXSourceResponse } from 'entities/perpDexsExplorer'

export const CHANGE_COLOR_FIELDS: (keyof PerpDEXSourceResponse)[] = [
  'volume1d',
  'volume7d',
  'volume30d',
  'volume',
  // 'traders1d',
  // 'traders7d',
  // 'traders30d',
  // 'traders',
  'oi1d',
  'oi7d',
  'oi30d',
  'oi',
  // 'longLiquidations1d',
  // 'longLiquidations7d',
  // 'longLiquidations30d',
  // 'longLiquidations',
  // 'shortLiquidations1d',
  // 'shortLiquidations7d',
  // 'shortLiquidations30d',
  // 'shortLiquidations',
  // 'liquidations1d',
  // 'liquidations7d',
  // 'liquidations30d',
  // 'liquidations',
  // 'revenue1d',
  // 'revenue7d',
  // 'revenue30d',
  // 'revenue',
]

export const NOT_CHANGE_COLOR_FIELDS: (keyof PerpDEXSourceResponse)[] = [
  'minTradingFee',
  'maxTradingFee',
  'makerFee',
  'takerFee',
  'borrowFee',
  'minCollateral',
  'minLeverage',
  'maxLeverage',
  'invested',
  'minReferralCommission',
  'maxReferralCommission',
  'traders1d',
  'traders7d',
  'traders30d',
  'traders',
  'revenue1d',
  'revenue7d',
  'revenue30d',
  'revenue',
  'longLiquidations1d',
  'longLiquidations7d',
  'longLiquidations30d',
  'longLiquidations',
  'shortLiquidations1d',
  'shortLiquidations7d',
  'shortLiquidations30d',
  'shortLiquidations',
  'liquidations1d',
  'liquidations7d',
  'liquidations30d',
  'liquidations',
  'avgPositionSize1d',
  'avgPositionSize7d',
  'avgPositionSize30d',
  'avgPositionSize',
]

export const FIELDS_WITH_IDEAL_VALUE: (keyof PerpDEXSourceResponse)[] = [
  'volume1d',
  'volume30d',
  'volume7d',
  'traders1d',
  'traders7d',
  'traders30d',
  'traders',
]

export const REFLECT_DATA_FIELDS: (keyof PerpDEXSourceResponse)[] = [
  'perpdex',
  'minTradingFee',
  'maxTradingFee',
  'makerFee',
  'takerFee',
  'borrowFee',
  'hasFundingFee',
  'type',
  'marginModes',
  'positionModes',
  'oneClickTrading',
  'collateralAssets',
  'minCollateral',
  'minLeverage',
  'maxLeverage',
  'minReferralCommission',
  'maxReferralCommission',
]
