import { PerpDEXSourceResponse } from 'entities/perpDexsExplorer'

export const FULL_TITLE_MAPPING: Partial<Record<keyof PerpDEXSourceResponse, string>> = {
  oi: 'OI - Open Interest (All)',
  oi1d: 'OI - Open Interest (1D)',
  oi7d: 'OI - Open Interest (7D)',
  oi30d: 'OI - Open Interest (30D)',
  oneClickTrading: 'One Click Trading',
  traders1d: 'DAU - Daily Active User (1D)',
  traders7d: 'WAU - Weekly Active User (7D)',
  traders30d: 'MAU - Monthly Active User (30D)',
  liquidations: 'LIQ - Liquidations (All)',
  liquidations1d: 'LIQ - Liquidations (1D)',
  liquidations7d: 'LIQ - Liquidations (7D)',
  liquidations30d: 'LIQ - Liquidations (30D)',
  longRatio: 'L/S Ratio - Long/Short Ratio (All)',
  longRatio1d: 'L/S Ratio - Long/Short Ratio (1D)',
  longRatio7d: 'L/S Ratio - Long/Short Ratio (7D)',
  longRatio30d: 'L/S Ratio - Long/Short Ratio (30D)',
  avgPositionDuration: 'APD - Average Position Duration (All)',
  avgPositionDuration1d: 'APD - Average Position Duration (1D)',
  avgPositionDuration7d: 'APD - Average Position Duration (7D)',
  avgPositionDuration30d: 'APD - Average Position Duration (30D)',
  avgPositionSize: 'APS - Average Position Size (All)',
  avgPositionSize1d: 'APS - Average Position Size (1D)',
  avgPositionSize7d: 'APS - Average Position Size (7D)',
  avgPositionSize30d: 'APS - Average Position Size (30D)',
  volumeShare1d: 'VS - Volume Share (1D)',
  volumeShare7d: 'VS - Volume Share (7D)',
  volumeShare30d: 'VS - Volume Share (30D)',
  volumeShare: 'VS - Volume Share (All)',
  feePerMillion1d: 'FPM - Fee Per Million (1D)',
  feePerMillion7d: 'FPM - Fee Per Million (7D)',
  feePerMillion30d: 'FPM - Fee Per Million (30D)',
  feePerMillion: 'FPM - Fee Per Million (All)',
  averageFeeRate1d: 'AFR - Average Fee Rate (1D)',
  averageFeeRate7d: 'AFR - Average Fee Rate (7D)',
  averageFeeRate30d: 'AFR - Average Fee Rate (30D)',
  averageFeeRate: 'AFR - Average Fee Rate (All)',
  openInterestShare1d: 'OIS - Open Interest Share (1D)',
  openInterestShare7d: 'OIS - Open Interest Share (7D)',
  openInterestShare30d: 'OIS - Open Interest Share (30D)',
  openInterestShare: 'OIS - Open Interest Share (All)',
  openInterestToVolumeRatio1d: 'OI/V - Open Interest to Volume Ratio (1D)',
  openInterestToVolumeRatio7d: 'OI/V - Open Interest to Volume Ratio (7D)',
  openInterestToVolumeRatio30d: 'OI/V - Open Interest to Volume Ratio (30D)',
  openInterestToVolumeRatio: 'OI/V - Open Interest to Volume Ratio (All)',
}

export const COMBINE_TITLE_MAPPING: Partial<Record<keyof PerpDEXSourceResponse, string>> = {
  minLeverage: 'Leverage',
  minReferralCommission: 'Referral Commission',
  minTradingFee: 'Trading Fee',
}

export const TITLE_MAPPING: Partial<Record<keyof PerpDEXSourceResponse, string>> = {
  volume1d: 'Volume (1D)',
  volume7d: 'Volume (7D)',
  volume30d: 'Volume (30D)',
  volumeShare1d: 'VS (1D)',
  volumeShare7d: 'VS (7D)',
  volumeShare30d: 'VS (30D)',
  volumeShare: 'VS (All)',
  feePerMillion1d: 'FPM (1D)',
  feePerMillion7d: 'FPM (7D)',
  feePerMillion30d: 'FPM (30D)',
  feePerMillion: 'FPM (All)',
  averageFeeRate1d: 'AFR (1D)',
  averageFeeRate7d: 'AFR (7D)',
  averageFeeRate30d: 'AFR (30D)',
  averageFeeRate: 'AFR (All)',
  openInterestShare1d: 'OIS (1D)',
  openInterestShare7d: 'OIS (7D)',
  openInterestShare30d: 'OIS (30D)',
  openInterestShare: 'OIS (All)',
  openInterestToVolumeRatio1d: 'OI/V (1D)',
  openInterestToVolumeRatio7d: 'OI/V (7D)',
  openInterestToVolumeRatio30d: 'OI/V (30D)',
  openInterestToVolumeRatio: 'OI/V (All)',
  oneClickTrading: '1CT',
  volume: 'Volume (All)',
  traders1d: 'DAU',
  traders7d: 'WAU',
  traders30d: 'MAU',
  traders: 'Traders (All)',
  traderPnl: 'Trader PnL (All)',
  traderPnl1d: 'Trader PnL (1D)',
  traderPnl7d: 'Trader PnL (7D)',
  traderPnl30d: 'Trader PnL (30D)',
  oi: 'OI (All)',
  oi1d: 'OI (1D)',
  oi7d: 'OI (7D)',
  oi30d: 'OI (30D)',
  longPnl: 'Long PnL (All)',
  longPnl1d: 'Long PnL (1D)',
  longPnl7d: 'Long PnL (7D)',
  longPnl30d: 'Long PnL (30D)',
  shortPnl: 'Short PnL (All)',
  shortPnl1d: 'Short PnL (1D)',
  shortPnl7d: 'Short PnL (7D)',
  shortPnl30d: 'Short PnL (30D)',
  longLiquidations: 'Long LIQ (All)',
  longLiquidations1d: 'Long LIQ (1D)',
  longLiquidations7d: 'Long LIQ (7D)',
  longLiquidations30d: 'Long LIQ (30D)',
  shortLiquidations: 'Short LIQ (All)',
  shortLiquidations1d: 'Short LIQ (1D)',
  shortLiquidations7d: 'Short LIQ (7D)',
  shortLiquidations30d: 'Short LIQ (30D)',
  avgPositionDuration: 'APD (All)',
  avgPositionDuration1d: 'APD (1D)',
  avgPositionDuration7d: 'APD (7D)',
  avgPositionDuration30d: 'APD (30D)',
  avgPositionSize: 'APS (All)',
  avgPositionSize1d: 'APS (1D)',
  avgPositionSize7d: 'APS (7D)',
  avgPositionSize30d: 'APS (30D)',
  longRatio: 'L/S Ratio (All)',
  longRatio1d: 'L/S Ratio (1D)',
  longRatio7d: 'L/S Ratio (7D)',
  longRatio30d: 'L/S Ratio (30D)',
  revenue: 'Revenue (All)',
  revenue1d: 'Revenue (1D)',
  revenue7d: 'Revenue (7D)',
  revenue30d: 'Revenue (30D)',
  liquidations: 'LIQ (All)',
  liquidations1d: 'LIQ (1D)',
  liquidations7d: 'LIQ (7D)',
  liquidations30d: 'LIQ (30D)',
  type: 'Type',
  marginModes: 'Margin Mode',
  positionModes: 'Position Mode',
  runTime: 'Runtime',
  collateralAssets: 'Collateral',
  minCollateral: 'Min Collateral',
  pairs: 'Pairs',
  token: 'Token',
  invested: 'Invested',
  audit: 'Audit',
  minTradingFee: 'Min Trading Fee',
  maxTradingFee: 'Max Trading Fee',
  makerFee: 'Maker Fee',
  takerFee: 'Taker Fee',
  borrowFee: 'Borrow Fee',
  hasFundingFee: 'Funding Fee',
  minReferralCommission: 'Min Referral Commission',
  maxReferralCommission: 'Max Referral Commission',
  rewards: 'Rewards',
  tradeUrl: 'Action',
  minLeverage: 'Min Leverage',
  maxLeverage: 'Max Leverage',
}
