export interface EventGoogleAnalytic {
  category: EventCategory
  action: string
  label: string
}

export enum EventSource {
  HOME = 'HOME',
  HOME_BACKTEST = 'HOME_BACKTEST',
  TRADER_PROFILE = 'TRADER_PROFILE',
  EVENT = 'EVENT',
  ONBOARDING_COPY_TRADE = 'ONBOARDING_COPY_TRADE',
}

export enum EventCategory {
  FILTER = 'FILTER',
  FAVORITES = 'FAVORITES',
  BACK_TEST = 'BACKTEST',
  COPY_TRADE = 'COPY_TRADE',
  MULTI_CHAIN = 'MULTI_CHAIN',
  ROUTES = 'ROUTES',
  SEARCH = 'SEARCH',
  LAYOUT = 'LAYOUT',
  CHART = 'CHART',
  COMPETITION = 'COMPETITION',
  LITE = 'LITE',
}

export const EVENT_ACTIONS = {
  [EventCategory.COPY_TRADE]: {
    OPEN_COPY_TRADE: 'open_copy_trade',
    REQUEST_COPY_TRADE: 'request_copy_trade',
    SUCCESS_COPY_TRADE: 'success_copy_trade',
    FAILED_COPY_TRADE: 'failed_copy_trade',
    CLONE_COPY_TRADE: 'clone_copy_trade',
    HOME_OPEN_COPY_TRADE: 'home_open_copy_trade',
    HOME_REQUEST_COPY_TRADE: 'home_request_copy_trade',
    HOME_SUCCESS_COPY_TRADE: 'home_success_copy_trade',
    HOME_FAILED_COPY_TRADE: 'home_failed_copy_trade',
    HOME_BACKTEST_OPEN_COPY_TRADE: 'home_backtest_open_copy_trade',
    HOME_BACKTEST_REQUEST_COPY_TRADE: 'home_backtest_request_copy_trade',
    HOME_BACKTEST_SUCCESS_COPY_TRADE: 'home_backtest_success_copy_trade',
    HOME_BACKTEST_FAILED_COPY_TRADE: 'home_backtest_failed_copy_trade',
    ONBOARDING_COPY_TRADE_SUCCESS: 'ONBOARDING_COPY_TRADE_SUCCESS',
    ONBOARDING_COPY_TRADE_FAIL: 'ONBOARDING_COPY_TRADE_FAIL',
  },
  [EventCategory.BACK_TEST]: {
    OPEN_SINGLE: 'open_backtest_single',
    OPEN_MULTIPLE: 'open_backtest_multiple',
    REQUEST_SINGLE: 'request_backtest_single',
    REQUEST_MULTIPLE: 'request_backtest_multiple',
    SET_STRATEGY_MULTIPLE: 'set_strategy_backtest_multiple',
    CONTINUE_MULTIPLE: 'continue_backtest_multiple',
    VIEW_RESULT: 'view_backtest_result',
    HOME_OPEN_SINGLE: 'home_open_backtest_single',
    HOME_REQUEST_SINGLE: 'home_request_backtest_single',
    HOME_SUCCESS_SINGLE: 'home_success_backtest_single',
    HOME_FAILED_SINGLE: 'home_failed_backtest_single',
    HOME_BACKTEST_D7: 'home_backtest_7_days',
    HOME_BACKTEST_D15: 'home_backtest_14_days',
    HOME_BACKTEST_D30: 'home_backtest_30_days',
    HOME_BACKTEST_D60: 'home_backtest_60_days',
  },
  [EventCategory.FILTER]: {
    CUSTOM_RANGE: 'filer_custom_range',
    SUGGESTION: 'filter_suggestion',
    NORMAL: 'filter_normal',
    RESET_DEFAULT: 'filter_reset_default',
    D7: 'filter_7_days',
    D15: 'filter_14_days',
    D30: 'filter_30_days',
    D60: 'filter_60_days',
    ALL_TIME: 'home_filter_all_time',
    HOME_DEFAULT: 'home_filter_default',
    HOME_TOP_PNL: 'home_filter_pnl',
    HOME_TOP_ROI: 'home_filter_roi',
    HOME_TOP_WIN_RATE: 'home_filter_win_rate',
    HOME_D7: 'home_filter_7_days',
    HOME_D15: 'home_filter_14_days',
    HOME_D30: 'home_filter_30_days',
    HOME_D60: 'home_filter_60_days',
    HOME_SOURCE_GMX: 'home_filter_GMX',
    HOME_SOURCE_GMX_V2: 'home_filter_GMX_V2',
    HOME_SOURCE_KWENTA: 'home_filter_KWENTA',
    HOME_SOURCE_POLINOMIAL: 'home_filter_POLINOMIAL',
  },
  [EventCategory.FAVORITES]: {
    ADD_FAVORITE_WITH_NOTE: 'add_favorite_with_note',
    ADD_FAVORITE_WITHOUT_NOTE: 'add_favorite_without_note',
    REMOVE_FAVORITE: 'remove_favorite',
    CANCEL_FAVORITE: 'cancel_favorite',
    OPEN_FAVORITES: 'open_favorites',
    HOME_OPEN_FAVORITES: 'home_open_favorites',
    HOME_CANCEL_FAVORITE: 'home_cancel_favorite',
  },
  [EventCategory.MULTI_CHAIN]: {
    SWITCH_GMX: 'switch_gmx',
    SWITCH_KWENTA: 'switch_kwenta',
    SWITCH_POLYNOMIAL: 'switch_polynomial',
  },
  [EventCategory.ROUTES]: {
    MY_PROFILE: 'my_profile',
    WALLET_MANAGEMENT: 'wallet_management',
    HISTORY: 'history',
    TOP_OPENING_POSITIONS_ALL: 'top_opening_positions_all',
    FAVORITES: 'favorites',
    JOIN_DISCORD: 'join_discord',
    JOIN_TELEGRAM: 'join_telegram',
    JOIN_TWITTER: 'join_twitter',
    JOIN_GITHUB: 'join_github',
    MY_REFERRAL: 'my_referral',
    ALERT_LIST: 'alert_list',
    USER_ACTIVITY: 'user_activity',
    SUBSCRIPTION: 'SUBSCRIPTION',
    USER_SUBSCRIPTION: 'USER_SUBSCRIPTION',
    HOME_EXPLORE_MORE: 'home_explorer_more',
    HOME_WALLET_MANAGEMENT: 'home_wallet_management',
    HOME_COPYTRADE_MANAGEMENT: 'home_copytrade_management',
    HOME_GETTING_STARTED: 'home_getting_started',
    HOME_POSITION_DETAILS: 'home_position_details',
    SECURITY: 'security',
  },
  [EventCategory.SEARCH]: {
    SEARCH_CLICK: 'search_click',
    SEARCH_ENTER: 'search_enter',
    SEARCH_CUSTOM_ADD: 'search_custom_add',
    SEARCH_VIEW_ALL: 'search_view_all',
    SEARCH_CLICK_POSITION: 'search_click_position',
    SEARCH_ENTER_POSITION: 'search_enter_position',
    SEARCH_VIEW_ALL_POSITIONS: 'search_view_all_positions',
  },
  [EventCategory.CHART]: {
    VIEW_ORDER_MARKER: 'view_order_marker',
  },
  [EventCategory.LAYOUT]: {
    EXPAND_EXPLORER_MAIN: 'expand_explorer_main',
    HIDE_EXPLORER_MAIN: 'expand_explorer_main',
    EXPAND_EXPLORER_LIST: 'expand_explorer_list',
    HIDE_EXPLORER_LIST: 'hide_explorer_list',
    EXPAND_EXPLORER_FILTER: 'expand_explorer_filter',
    HIDE_EXPLORER_FILTER: 'hide_explorer_filter',
    SHOW_HEATMAP_ACTIVITY: 'show_trader_heatmap_activity',
    HIDE_HEATMAP_ACTIVITY: 'hide_trader_heatmap_activity',
    SHOW_PNL_CHART: 'show_trader_pnl_chart',
    HIDE_PNL_CHART: 'hide_trader_pnl_chart',
    EXPAND_POSITION_FULL: 'expand_trader_position_full',
    HIDE_POSITION_FULL: 'hide_trader_position_full',
    EXPAND_POSITION_TOP: 'expand_trader_position_top',
    HIDE_POSITION_TOP: 'hide_trader_position_top',
    EXPAND_OPENING_POSITION_FULL: 'expand_trader_opening_position_full',
    HIDE_OPENING_POSITION_FULL: 'hide_trader_opening_position_full',
    EXPAND_CHART_POSITION_FULL: 'expand_chart_position_full',
    HIDE_CHART_POSITION_FULL: 'hide_chart_position_full',
  },
  [EventCategory.COMPETITION]: {
    HOME_CLICK_NAV: 'comp_home_click_nav',
    HOME_CLICK_BANNER: 'comp_home_click_banner',
    EVENT_CLICK_CONNECT_WALLET: 'comp_event_click_connect_wallet',
    EVENT_CLICK_REGISTER: 'comp_event_click_register',
    EVENT_CLICK_COPYTRADE: 'comp_event_click_copytrade',
    EVENT_CLICK_VIEW_BLOG: 'comp_event_click_blog',
    EVENT_CLICK_TELEGRAM: 'comp_event_click_telegram',
    EVENT_CLICK_VIEW_ACCOUNTS: 'comp_event_view_accounts',
    EVENT_REGISTER_ELIGIBLE: 'comp_event_eligible',
    EVENT_REGISTER_NOT_ELIGIBLE: 'comp_event_not_eligible',
    EVENT_REGISTER_ERROR: 'comp_event_register_error',
  },
  [EventCategory.LITE]: {
    LITE_START_ONBOARDING: 'lite_start_onboarding',
    LITE_FIND_TRADER: 'lite_find_trader',
    LITE_SKIP_ONBOARDING: 'lite_skip_onboarding',
    LITE_BACKTEST_TRADER: 'lite_backtest_trader',
    LITE_PREVIEW_TRADER: 'lite_preview_trader',
    LITE_COPY_TRADER_START: 'lite_copy_trader_start',
    LITE_COPY_TRADER_SUCCESS: 'lite_copy_trader_success',
    LITE_COPY_TRADER_FAILED: 'lite_copy_trader_failed',
    LITE_COPY_TRADER_CANCEL: 'lite_copy_trader_cancel',
    LITE_COPY_USE_RECOMMEDATION_SETTINGS: 'lite_copy_use_recommendation_settings',
    LITE_ONBOARDING_NAVIGATE_TO_LITE: 'lite_onboarding_navigate_to_lite',
    LITE_UPGRADE: 'lite_upgrade',
  },
}
