import { PermissionData } from 'entities/permission'
import { ProtocolEnum } from 'utils/config/enums'

export const SUBSCRIPTION_PERMISSION_DATA = {
  PROTOCOL: {
    NON_LOGIN: {
      isEnabled: true,
      protocolAllowed: ['GMX', 'GMX_AVAX', 'HMX_ARB', 'DYDX'],
    },
    FREE: {
      isEnabled: true,
      protocolAllowed: ['GMX', 'GMX_AVAX', 'HMX_ARB', 'DYDX'],
    },
    STARTER: {
      isEnabled: true,
      protocolAllowed: [
        'GMX',
        'GMX_AVAX',
        'HMX_ARB',
        'DYDX',
        'APOLLOX_BNB',
        'APOLLOX_BASE',
        'SYNFUTURE_BASE',
        'BMX_BASE',
        'ELFI_ARB',
        'FOXIFY_ARB',
        'HORIZON_BNB',
        'DEPERP_BASE',
      ],
    },
    PRO: {
      isEnabled: true,
      protocolAllowed: [
        'GMX',
        'GMX_AVAX',
        'HMX_ARB',
        'DYDX',
        'APOLLOX_BNB',
        'APOLLOX_BASE',
        'SYNFUTURE_BASE',
        'BMX_BASE',
        'ELFI_ARB',
        'FOXIFY_ARB',
        'HORIZON_BNB',
        'DEPERP_BASE',
        'GNS',
        'GNS_POLY',
        'GNS_BASE',
        'GNS_APE',
        'KILOEX_OPBNB',
        'KILOEX_BNB',
        'KILOEX_MANTA',
        'KILOEX_BASE',
        'SYNTHETIX_V3',
        'SYNTHETIX_V3_ARB',
        'AVANTIS_BASE',
        'POLYNOMIAL',
        'POLYNOMIAL_L2',
        'VERTEX_ARB',
        'MUX_ARB',
        'LEVEL_BNB',
        'LEVEL_ARB',
        'LINEHUB_LINEA',
        'UNIDEX_ARB',
        'YFX_ARB',
        'PINGU_ARB',
        'BSX_BASE',
        'CYBERDEX',
        'DEXTORO',
        'KTX_MANTLE',
        'ZENO_METIS',
        'ROLLIE_SCROLL',
        'GMX_V2_AVAX',
        'GMX_V2',
        'GMX_SOL',
        'MYX_ARB',
        'MYX_LINEA',
        'MYX_OPBNB',
        'SYNTHETIX',
        'KWENTA',
      ],
    },
    ELITE: {
      isEnabled: true,
      protocolAllowed: [
        'GMX',
        'GMX_AVAX',
        'HMX_ARB',
        'DYDX',
        'APOLLOX_BNB',
        'APOLLOX_BASE',
        'SYNFUTURE_BASE',
        'BMX_BASE',
        'ELFI_ARB',
        'FOXIFY_ARB',
        'HORIZON_BNB',
        'DEPERP_BASE',
        'GNS',
        'GNS_POLY',
        'GNS_BASE',
        'GNS_APE',
        'KILOEX_OPBNB',
        'KILOEX_BNB',
        'KILOEX_MANTA',
        'KILOEX_BASE',
        'SYNTHETIX_V3',
        'SYNTHETIX_V3_ARB',
        'AVANTIS_BASE',
        'POLYNOMIAL',
        'POLYNOMIAL_L2',
        'VERTEX_ARB',
        'MUX_ARB',
        'LEVEL_BNB',
        'LEVEL_ARB',
        'LINEHUB_LINEA',
        'UNIDEX_ARB',
        'YFX_ARB',
        'PINGU_ARB',
        'BSX_BASE',
        'CYBERDEX',
        'DEXTORO',
        'KTX_MANTLE',
        'ZENO_METIS',
        'ROLLIE_SCROLL',
        'GMX_V2_AVAX',
        'GMX_V2',
        'GMX_SOL',
        'MYX_ARB',
        'MYX_LINEA',
        'MYX_OPBNB',
        'SYNTHETIX',
        'KWENTA',
        'HYPERLIQUID',
        'JUPITER',
        'LOGX_BLAST',
        'LOGX_MODE',
        'MUMMY_FANTOM',
        'VELA_ARB',
        'MORPHEX_FANTOM',
        'EQUATION_ARB',
        'PERENNIAL_ARB',
      ],
    },
  },
  TRADER_EXPLORER: {
    NON_LOGIN: {
      protocol: [ProtocolEnum.APOLLOX_BASE],
      fieldsAllowed: [],
      isEnableLatestActivities: false,
      isEnableRankingFilter: false,
      isEnableCexDepth: false,
      maxFilterFields: 1,
      exportExcelQuota: 0,
    },
    FREE: {
      protocol: [ProtocolEnum.APOLLOX_BASE],
      fieldsAllowed: ['account', 'pnl'],
      isEnableLatestActivities: false,
      isEnableRankingFilter: false,
      isEnableCexDepth: false,
      maxFilterFields: 1,
      exportExcelQuota: 0,
    },
    STARTER: {
      protocol: [ProtocolEnum.APOLLOX_BASE],
      fieldsAllowed: ['account', 'pnl', 'realisedPnl', 'totalFee'],
      isEnableLatestActivities: false,
      isEnableRankingFilter: false,
      isEnableCexDepth: false,
      maxFilterFields: 1,
      exportExcelQuota: 0,
    },
    PRO: {
      protocol: [ProtocolEnum.APOLLOX_BASE, ProtocolEnum.GNS],
      fieldsAllowed: ['account', 'pnl', 'realisedPnl', 'totalFee', 'totalGain', 'totalLoss'],
      isEnableLatestActivities: false,
      isEnableRankingFilter: false,
      isEnableCexDepth: false,
      maxFilterFields: 1,
      exportExcelQuota: 0,
    },
    ELITE: {
      protocol: [ProtocolEnum.APOLLOX_BASE],
      fieldsAllowed: [
        'account',
        'pnl',
        'realisedPnl',
        'totalFee',
        'totalGain',
        'totalLoss',
        'minDuration',
        'maxDuration',
      ],
      isEnableLatestActivities: false,
      isEnableRankingFilter: true,
      isEnableCexDepth: false,
      maxFilterFields: 1,
      exportExcelQuota: 0,
    },
  },
  COPY_TRADINGL: {
    NON_LOGIN: {
      isEnabled: false,
      exchangeAllowed: [],
      apiKeyQuota: 0,
      copyTradeQuota: 0,
    },
    FREE: {
      isEnabled: true,
      exchangeAllowed: ['BITGET', 'HYPERLIQUID', 'GATE'],
      apiKeyQuota: 1,
      copyTradeQuota: 5,
    },
    STARTER: {
      isEnabled: true,
      exchangeAllowed: ['BITGET', 'HYPERLIQUID', 'GATE', 'OKX', 'BINGX'],
      apiKeyQuota: 2,
      copyTradeQuota: 10,
    },
    PRO: {
      isEnabled: true,
      exchangeAllowed: ['BITGET', 'HYPERLIQUID', 'GATE', 'OKX', 'BINGX', 'BYBIT'],
      apiKeyQuota: 5,
      copyTradeQuota: 50,
    },
    ELITE: {
      isEnabled: true,
      exchangeAllowed: ['BITGET', 'HYPERLIQUID', 'GATE', 'OKX', 'BINGX', 'BYBIT', 'BINANCE'],
      apiKeyQuota: 10,
      copyTradeQuota: 150,
    },
  },
} as unknown as PermissionData
