import { ProtocolEnum } from './enums'

export const QUERY_KEYS = {
  GET_SYSTEM_STATS: 'GET_SYSTEM_STATS',
  GET_SYSTEM_STATS_OVERVIEW: 'GET_SYSTEM_STATS_OVERVIEW',
  GET_TOP_TRADERS: 'GET_TOP_TRADERS',
  GET_TRADER_DETAIL: 'GET_TRADER_DETAIL',
  GET_TOKEN_TRADES_BY_TRADER: 'GET_TOKEN_TRADES_BY_TRADER',
  GET_POSITIONS_OPEN: 'GET_POSITIONS_OPEN',
  GET_POSITIONS_HISTORY: 'GET_POSITIONS_HISTORY',
  GET_POSITION_DETAIL: 'GET_POSITION_DETAIL',
  GET_COPY_TRADE_SETTINGS: 'GET_COPY_TRADE_SETTINGS',
  GET_COPY_TRADE_SETTING_DETAIL: 'GET_COPY_TRADE_SETTING_DETAIL',
  GET_MY_COPY_POSITIONS: 'GET_MY_COPY_POSITIONS',
  GET_MY_COPY_TRADERS: 'GET_MY_COPY_TRADERS',
  GET_ALL_MY_COPY_TRADERS: 'GET_ALL_MY_COPY_TRADERS',
  GET_MY_COPY_POSITION_DETAIL: 'GET_MY_COPY_POSITION_DETAIL',
  GET_MY_COPY_ORDERS: 'GET_MY_COPY_ORDERS',
  GET_MY_PNL_DATA: 'GET_MY_PNL_DATA',
  GET_CHART_DATA: 'GET_CHART_DATA',
  GET_TRADER_PNL_STATISTIC: 'GET_TRADER_PNL_STATISTIC',
  GET_TRADER_FILTER_COUNTER: 'GET_TRADER_FILTER_COUNTER',
  GET_TRADER_FILTER_SUGGESTIONS: 'GET_TRADER_FILTER_SUGGESTIONS',
  GET_TRADERS_COPYING: 'GET_TRADERS_COPYING',
  GET_TOP_OPEN_POSITIONS: 'GET_TOP_OPEN_POSITIONS',
  GET_PRE_DELETE_DATA: 'GET_PRE_DELETE_DATA',
  GET_SHARED_BACKTEST_DATA: 'GET_SHARED_BACKTEST_DATA',
  GET_SHARED_POSITION_DATA: 'GET_SHARED_POSITION_DATA',
  GET_COPY_TRADE_CONFIGS: 'GET_COPY_TRADE_CONFIGS',
  GET_COPY_TRADE_CONFIGS_BY_ID: 'GET_COPY_TRADE_CONFIGS_BY_ID',
  GET_COPY_TRADE_CONFIGS_BY_KEY: 'GET_COPY_TRADE_CONFIGS_BY_KEY',
  GET_REFERRAL_LIST: 'GET_REFERRAL_LIST',
  GET_REFERRAL_STATS: 'GET_REFERRAL_STATS',
  GET_COPY_WALLETS_LIST: 'GET_COPY_WALLETS_LIST',
  GET_USER_ACTIVITY_LOGS: 'GET_USER_ACTIVITY_LOGS',
  GET_AVAILABLE_MARGIN: 'GET_AVAILABLE_MARGIN',
}

export const CONTRACT_QUERY_KEYS = {
  NATIVE: 'NATIVE',
  USDC: 'USDC',
  BRIDGED_USDC: 'BRIDGED_USDC',
  WBTC: 'WBTC',
  ERC20: 'ERC20',
  SMART_ACCOUNT: 'SMART_ACCOUNT',
  SMART_ACCOUNT_FACTORY: 'SMART_ACCOUNT_FACTORY',
  SUSD: 'SUSD',
  MULTICALL: 'MULTICALL',
  DELEGATE: 'DELEGATE',
  SYNTHETIX_MARKET: 'SYNTHETIX_MARKET',
} as const

export const STORAGE_KEYS = {
  JWT: 'copin-jwt',
  WALLET: 'copin-wallet',
  ACCOUNT: 'copin-account',
  UNVERIFIED_ACCOUNT: 'unverified-account',
  CONDITIONAL_FILTERS: 'conditional-filter', // TODO NEXT: keep to last deploy
  DEFAULT_FILTERS: 'default-filters',
  RANKING_FILTERS: 'ranking-filters',
  FILTER_TAB: 'filter-tab',
  SHOW_CHART: 'show-chart',
  HOME_DESKTOP_LAYOUT: 'home-desktop-layout',
  MY_COPY_DATA: 'my-copy-data',
  MY_COPY_WALLET: 'my-copy-wallet',
  MY_HISTORY_TRADERS: 'my-history-traders',
  BACKTEST_GUIDE: 'backtest-guide',
}

export const URL_PARAM_KEYS = {
  EXPLORER_TIME_FILTER: 'time',
  EXPLORER_TIME_RANGE_FILTER: 'range',
  FAVORITE_TIME_RANGE_FILTER: 'time-favorite',
  FAVORITE_TIME_FILTER: 'range-favorite',
  EXPLORER_PAGE: 'page',
  EXPLORER_LIMIT: 'limit',
  CURRENCY: 'currency',
  WHAT_IF_NEXT_HOURS: 'next_hours',
  BACKTEST_DATA: 'backtest_data',
  OPEN_BACKTEST_MODAL: 'open_backtest_modal',
  DEFAULT_FILTERS: 'default_filters',
  RANKING_FILTERS: 'ranking_filters',
  FILTER_TAB: 'filter_tab',
  TRADER_HISTORY_PAGE: 'history_page',
  MY_PROFILE_HISTORY_PAGE: 'my_history_page',
  MY_PROFILE_HISTORY_LIMIT: 'my_history_limit',
  MY_PROFILE_OPENINGS_PAGE: 'my_openings_page',
  MY_PROFILE_ALL_HISTORY_PAGE: 'my_all_history_page',
  MY_PROFILE_ALL_HISTORY_LIMIT: 'my_all_history_limit',
  MY_COPY_MAIN_SECTION_TAB: 'section_tab',
  MY_COPIES_STATUS: 'copies_status',
  MY_COPIES_PROTOCOL: 'copies_protocol',
  MY_POSITIONS_STATUS: 'positions_status',
  MY_POSITIONS_ENTRY_STATUS: 'entry_status',
  USER_ACTIVITY_PAGE: 'activity_page',
}

export const TOOLTIP_KEYS = {
  MY_COPY_ICON_REVERSE: 'my_copy_icon_reverse',
  MY_COPY_ICON_STOPLOSS: 'my_copy_icon_stoploss',
  MY_COPY_ICON_MAX_VOL_MULTIPLIER: 'my_copy_icon_max_vol_multiplier',
}

export const ELEMENT_IDS = {
  TRADER_CHART_PNL: 'trader-chart-pnl-container',
  POSITION_CHART_PNL: 'position-chart-pnl-container',
}

export const ELEMENT_CLASSNAMES = {
  TRADER_ADDRESS: 'trader_address',
}

export const SERVICE_KEYS = {
  [ProtocolEnum.GMX]: 'INTERNAL_TEST',
  [ProtocolEnum.KWENTA]: 'TEST_KWENTA',
}
