import { ProtocolTokenMapping } from './trades'

const ROLLIE_SCROLL_PAIRS = {
  'ROLLIE_SCROLL-0': 'ETH',
  'ROLLIE_SCROLL-1': 'BTC',
  'ROLLIE_SCROLL-2': 'BNB',
  'ROLLIE_SCROLL-3': 'XRP',
  'ROLLIE_SCROLL-4': 'ADA',
  'ROLLIE_SCROLL-5': 'DOT',
  'ROLLIE_SCROLL-6': 'LINK',
  'ROLLIE_SCROLL-7': 'LTC',
  'ROLLIE_SCROLL-8': 'BCH',
  'ROLLIE_SCROLL-9': 'ATOM',
  'ROLLIE_SCROLL-10': 'UNI',
  'ROLLIE_SCROLL-11': 'OP',
  'ROLLIE_SCROLL-12': 'ARB',
  'ROLLIE_SCROLL-13': 'TRX',
  'ROLLIE_SCROLL-14': 'SUI',
  'ROLLIE_SCROLL-15': 'NEAR',
  'ROLLIE_SCROLL-16': 'PYTH',
  'ROLLIE_SCROLL-17': 'PEPE',
  'ROLLIE_SCROLL-18': 'FIL',
  'ROLLIE_SCROLL-19': 'LDO',
  'ROLLIE_SCROLL-20': 'TON',
  'ROLLIE_SCROLL-21': 'MATIC',
  'ROLLIE_SCROLL-22': 'SHIB',
  'ROLLIE_SCROLL-23': 'DOGE',
  'ROLLIE_SCROLL-24': 'AVAX',
  'ROLLIE_SCROLL-25': 'SOL',
  'ROLLIE_SCROLL-26': 'BONK',
  'ROLLIE_SCROLL-27': 'WIF',
  'ROLLIE_SCROLL-28': 'APT',
  'ROLLIE_SCROLL-29': 'STX',
  'ROLLIE_SCROLL-30': 'AAVE',
  'ROLLIE_SCROLL-31': 'STRK',
  'ROLLIE_SCROLL-32': 'XLM',
  'ROLLIE_SCROLL-33': 'FTM',
  'ROLLIE_SCROLL-34': 'SEI',
  'ROLLIE_SCROLL-35': 'GRT',
  'ROLLIE_SCROLL-36': 'VET',
  'ROLLIE_SCROLL-37': 'ORDI',
  'ROLLIE_SCROLL-38': 'WLD',
  'ROLLIE_SCROLL-39': 'CHZ',
  'ROLLIE_SCROLL-40': 'EOS',
  'ROLLIE_SCROLL-41': 'FLOKI',
  'ROLLIE_SCROLL-42': 'BOME',
  'ROLLIE_SCROLL-43': 'ETC',
  'ROLLIE_SCROLL-44': 'ENA',
  'ROLLIE_SCROLL-45': 'RUNE',
  'ROLLIE_SCROLL-46': 'TIA',
  'ROLLIE_SCROLL-47': 'JUP',
  'ROLLIE_SCROLL-48': 'ICP',
  'ROLLIE_SCROLL-49': 'MEW',
  'ROLLIE_SCROLL-50': 'POPCAT',
  'ROLLIE_SCROLL-51': 'APE',
  'ROLLIE_SCROLL-52': 'W',
  'ROLLIE_SCROLL-53': 'SCR',
}

const TOKEN_TRADE_ROLLIE_SCROLL = Object.entries(ROLLIE_SCROLL_PAIRS).reduce<ProtocolTokenMapping>(
  (result, [key, value]) => {
    return {
      ...result,
      [key]: {
        symbol: value,
      },
    }
  },
  {}
)

export { TOKEN_TRADE_ROLLIE_SCROLL }
