import { PYTH_IDS_MAPPING } from './pythIds'

const TOKEN_TRADE_SYNTHETIX_V3 = {
  'SYNTHETIX_V3-100': {
    address: 'SYNTHETIX_V3-100',
    name: 'ETH',
    symbol: 'ETH',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-200': {
    address: 'SYNTHETIX_V3-200',
    name: 'BTC',
    symbol: 'BTC',
    decimals: 8,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-300': {
    address: 'SYNTHETIX_V3-300',
    name: 'SNX',
    symbol: 'SNX',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-400': {
    address: 'SYNTHETIX_V3-400',
    name: 'SOL',
    symbol: 'SOL',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-500': {
    address: 'SYNTHETIX_V3-500',
    name: 'WIF',
    symbol: 'WIF',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-600': {
    address: 'SYNTHETIX_V3-600',
    name: 'W',
    symbol: 'W',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-700': {
    address: 'SYNTHETIX_V3-700',
    name: 'ENA',
    symbol: 'ENA',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-800': {
    address: 'SYNTHETIX_V3-800',
    name: 'DOGE',
    symbol: 'DOGE',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-900': {
    address: 'SYNTHETIX_V3-900',
    name: 'AVAX',
    symbol: 'AVAX',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1000': {
    address: 'SYNTHETIX_V3-1000',
    name: 'OP',
    symbol: 'OP',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1100': {
    address: 'SYNTHETIX_V3-1100',
    name: 'ORDI',
    symbol: 'ORDI',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1200': {
    address: 'SYNTHETIX_V3-1200',
    name: 'PEPE',
    symbol: 'PEPE',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1300': {
    address: 'SYNTHETIX_V3-1300',
    name: 'RUNE',
    symbol: 'RUNE',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1400': {
    address: 'SYNTHETIX_V3-1400',
    name: 'BONK',
    symbol: 'BONK',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1500': {
    address: 'SYNTHETIX_V3-1500',
    name: 'FTM',
    symbol: 'FTM',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1600': {
    address: 'SYNTHETIX_V3-1600',
    name: 'ARB',
    symbol: 'ARB',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1700': {
    address: 'SYNTHETIX_V3-1700',
    name: 'MATIC',
    symbol: 'MATIC',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1800': {
    address: 'SYNTHETIX_V3-1800',
    name: 'BNB',
    symbol: 'BNB',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-1900': {
    address: 'SYNTHETIX_V3-1900',
    name: 'LINK',
    symbol: 'LINK',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2000': {
    address: 'SYNTHETIX_V3-2000',
    name: 'PENDLE',
    symbol: 'PENDLE',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2100': {
    address: 'SYNTHETIX_V3-2100',
    name: 'INJ',
    symbol: 'INJ',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2200': {
    address: 'SYNTHETIX_V3-2200',
    name: 'GMX',
    symbol: 'GMX',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2300': {
    address: 'SYNTHETIX_V3-2300',
    name: 'TIA',
    symbol: 'TIA',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2400': {
    address: 'SYNTHETIX_V3-2400',
    name: 'SUI',
    symbol: 'SUI',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2500': {
    address: 'SYNTHETIX_V3-2500',
    name: 'TON',
    symbol: 'TON',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2600': {
    address: 'SYNTHETIX_V3-2600',
    name: 'ARKM',
    symbol: 'ARKM',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2700': {
    address: 'SYNTHETIX_V3-2700',
    name: 'GALA',
    symbol: 'GALA',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2800': {
    address: 'SYNTHETIX_V3-2800',
    name: 'TAO',
    symbol: 'TAO',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-2900': {
    address: 'SYNTHETIX_V3-2900',
    name: 'BOME',
    symbol: 'BOME',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-3000': {
    address: 'SYNTHETIX_V3-3000',
    name: 'ETHFI',
    symbol: 'ETHFI',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-3100': {
    address: 'SYNTHETIX_V3-3100',
    name: 'STX',
    symbol: 'STX',
    decimals: 18,
    priceFeedId: '',
  },
  'SYNTHETIX_V3-3200': {
    address: 'SYNTHETIX_V3-3200',
    name: 'AXL',
    symbol: 'AXL',
    decimals: 18,
    priceFeedId: '',
  },
}
for (const key in TOKEN_TRADE_SYNTHETIX_V3) {
  const values = TOKEN_TRADE_SYNTHETIX_V3[key as keyof typeof TOKEN_TRADE_SYNTHETIX_V3]
  values.priceFeedId = PYTH_IDS_MAPPING[values.symbol as keyof typeof PYTH_IDS_MAPPING] ?? ''
}
export { TOKEN_TRADE_SYNTHETIX_V3 }
